# Generated by Django 3.2.12 on 2022-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='fault.jpg', upload_to='profile_pics'),
        ),
    ]
