# Generated by Django 3.2.12 on 2022-02-16 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_registration_number', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('take_off_city', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('fare', models.FloatField()),
                ('departure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_MOMO_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailableBuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('current_city', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('fare', models.FloatField()),
                ('departure_time', models.CharField(max_length=30)),
                ('number_of_seats_available', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('company_Info', models.TextField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
