# Generated by Django 3.2.12 on 2022-02-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedBusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_registration_number', models.CharField(max_length=10)),
                ('take_off_city', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('departure_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoadedBusInfoView',
            fields=[
                ('passengerbookings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.passengerbookings')),
            ],
            bases=('reservations.passengerbookings',),
        ),
    ]
