# Generated by Django 3.2.12 on 2022-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_loadedbusinfoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebuses',
            name='fare',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passengerbookings',
            name='fare',
            field=models.IntegerField(),
        ),
    ]
