# Generated by Django 3.2.12 on 2022-03-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20220302_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Enter_Your_MOMO_Number',
            field=models.CharField(max_length=15),
        ),
    ]
