# Generated by Django 3.2.12 on 2022-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_payment_enter_your_momo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_company_name', models.CharField(max_length=50)),
                ('payee_account_number', models.CharField(max_length=50)),
                ('transfer_date_time', models.DateTimeField()),
                ('transfer_amount', models.IntegerField()),
            ],
        ),
    ]
